CREATE SEQUENCE "ASSESSMENT_ITEM_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "ASSESSMENT_ITEM" (
  "ASSESSMENT_ITEM_ID" NUMBER(9) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_ASSESSMENT_ITEM PRIMARY KEY ("ASSESSMENT_ITEM_ID")
);

COMMENT ON TABLE "ASSESSMENT_ITEM" IS '評価項目';
COMMENT ON COLUMN "ASSESSMENT_ITEM"."ASSESSMENT_ITEM_ID" IS '評価項目ID';
COMMENT ON COLUMN "ASSESSMENT_ITEM"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "ASSESSMENT_ITEM"."UPDATED_AT" IS '更新日時';
