CREATE SEQUENCE "GOAL_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "GOAL_HEADER" (
  "GOAL_ID" NUMBER(9) NOT NULL,
  "USER_ID" NUMBER(9) NOT NULL,
  "ASSESSMENT_ID" NUMBER(9) NOT NULL,
  "TITLE" VARCHAR2(256) NOT NULL,
  "CONTENT" VARCHAR2(256),
  "STATUS" VARCHAR2(20) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_GOAL PRIMARY KEY ("GOAL_ID"),
  CONSTRAINT FK_GOAL_USER FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID"),
  CONSTRAINT FK_GOAL_ASSESSMENT FOREIGN KEY ("ASSESSMENT_ID") REFERENCES "ASSESSMENT_HEADER" ("ASSESSMENT_ID"),
  CONSTRAINT UQ_GOAL UNIQUE ("USER_ID", "ASSESSMENT_ID")
);

COMMENT ON TABLE "GOAL_HEADER" IS '目標ヘッダー';
COMMENT ON COLUMN "GOAL_HEADER"."GOAL_ID" IS '目標ID';
COMMENT ON COLUMN "GOAL_HEADER"."USER_ID" IS 'ユーザID';
COMMENT ON COLUMN "GOAL_HEADER"."ASSESSMENT_ID" IS '評価ID';
COMMENT ON COLUMN "GOAL_HEADER"."TITLE" IS 'タイトル';
COMMENT ON COLUMN "GOAL_HEADER"."CONTENT" IS 'コンテキスト';
COMMENT ON COLUMN "GOAL_HEADER"."STATUS" IS 'ステータス';
COMMENT ON COLUMN "GOAL_HEADER"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "GOAL_HEADER"."UPDATED_AT" IS '更新日時';

CREATE TABLE "GOAL_DETAIL" (
  "GOAL_ID" NUMBER(9) NOT NULL,
  "SEQ" NUMBER(9) NOT NULL,
  "TITLE" VARCHAR2(256) NOT NULL,
  "CONTENT" VARCHAR2(256),
  "STATUS" VARCHAR2(20) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_GOAL_DETAIL PRIMARY KEY ("GOAL_ID", "SEQ"),
  CONSTRAINT FK_GOAL_DETAIL_GOAL FOREIGN KEY ("GOAL_ID") REFERENCES "GOAL_HEADER" ("GOAL_ID")
);

COMMENT ON TABLE "GOAL_DETAIL" IS '目標詳細';
COMMENT ON COLUMN "GOAL_DETAIL"."GOAL_ID" IS '目標ID';
COMMENT ON COLUMN "GOAL_DETAIL"."SEQ" IS 'シーケンス';
COMMENT ON COLUMN "GOAL_DETAIL"."TITLE" IS 'タイトル';
COMMENT ON COLUMN "GOAL_DETAIL"."CONTENT" IS 'コンテキスト';
COMMENT ON COLUMN "GOAL_DETAIL"."STATUS" IS 'ステータス';
COMMENT ON COLUMN "GOAL_DETAIL"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "GOAL_DETAIL"."UPDATED_AT" IS '更新日時';