CREATE SEQUENCE "PLAN_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "PLAN_HEADER" (
  "PLAN_ID" NUMBER(9) NOT NULL,
  "USER_ID" NUMBER(9) NOT NULL,
  "GOAL_ID" NUMBER(9) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "STATUS" VARCHAR2(20) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_PLAN PRIMARY KEY ("PLAN_ID"),
  CONSTRAINT FK_PLAN_USER FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID"),
  CONSTRAINT FK_PLAN_GOAL FOREIGN KEY ("GOAL_ID") REFERENCES "GOAL_HEADER" ("GOAL_ID"),
  CONSTRAINT UQ_PLAN UNIQUE ("USER_ID", "GOAL_ID")
);

COMMENT ON TABLE "PLAN_HEADER" IS '計画ヘッダー';
COMMENT ON COLUMN "PLAN_HEADER"."PLAN_ID" IS '計画ID';
COMMENT ON COLUMN "PLAN_HEADER"."USER_ID" IS 'ユーザID';
COMMENT ON COLUMN "PLAN_HEADER"."GOAL_ID" IS '目標ID';
COMMENT ON COLUMN "PLAN_HEADER"."START_DATE" IS '開始日';
COMMENT ON COLUMN "PLAN_HEADER"."END_DATE" IS '終了日';
COMMENT ON COLUMN "PLAN_HEADER"."STATUS" IS 'ステータス';
COMMENT ON COLUMN "PLAN_HEADER"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "PLAN_HEADER"."UPDATED_AT" IS '更新日時';

CREATE TABLE "PLAN_DETAIL" (
  "PLAN_ID" NUMBER(9) NOT NULL,
  "SEQ" NUMBER(9) NOT NULL,
  "TITLE" VARCHAR2(256) NOT NULL,
  "CONTENT" VARCHAR2(256) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE NOT NULL,
  "STATUS" VARCHAR2(20) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_PLAN_DETAIL PRIMARY KEY ("PLAN_ID", "SEQ"),
  CONSTRAINT FK_PLAN_DETAIL_PLAN FOREIGN KEY ("PLAN_ID") REFERENCES "PLAN_HEADER" ("PLAN_ID")
);

COMMENT ON TABLE "PLAN_DETAIL" IS '計画詳細';
COMMENT ON COLUMN "PLAN_DETAIL"."PLAN_ID" IS '計画ID';
COMMENT ON COLUMN "PLAN_DETAIL"."SEQ" IS 'シーケンス';
COMMENT ON COLUMN "PLAN_DETAIL"."TITLE" IS 'タイトル';
COMMENT ON COLUMN "PLAN_DETAIL"."CONTENT" IS '内容';
COMMENT ON COLUMN "PLAN_DETAIL"."START_DATE" IS '開始日';
COMMENT ON COLUMN "PLAN_DETAIL"."END_DATE" IS '終了日';
COMMENT ON COLUMN "PLAN_DETAIL"."STATUS" IS 'ステータス';
COMMENT ON COLUMN "PLAN_DETAIL"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "PLAN_DETAIL"."UPDATED_AT" IS '更新日時';
