CREATE SEQUENCE "GROUP_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "GROUP" (
  "GROUP_ID" NUMBER(9) DEFAULT NOT NULL,
  "NAME" VARCHAR2(50 CHAR) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_GROUP PRIMARY KEY ("GROUP_ID")
);

COMMENT ON TABLE "GROUP" IS '組織';
COMMENT ON COLUMN "GROUP"."GROUP_ID" IS '組織ID';
COMMENT ON COLUMN "GROUP"."NAME" IS '組織名';
COMMENT ON COLUMN "GROUP"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "GROUP"."UPDATED_AT" IS '更新日時';
