CREATE SEQUENCE "ASSESSMENT_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "ASSESSMENT_HEADER" (
  "ASSESSMENT_ID" NUMBER(9) NOT NULL,
  "USER_ID" NUMBER(9) NOT NULL,
  "MONTH" DATE NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_ASSESSMENT_HEADER PRIMARY KEY ("ASSESSMENT_ID"),
  CONSTRAINT FK_ASSESSMENT_USER FOREIGN KEY ("USER_ID") REFERENCES "USER" ("USER_ID"),
  CONSTRAINT UQ_ASSESSMENT_HEADER UNIQUE ("USER_ID", "MONTH")
);

COMMENT ON TABLE "ASSESSMENT_HEADER" IS '評価ヘッダー';
COMMENT ON COLUMN "ASSESSMENT_HEADER"."ASSESSMENT_ID" IS '評価ID';
COMMENT ON COLUMN "ASSESSMENT_HEADER"."USER_ID" IS 'ユーザID';
COMMENT ON COLUMN "ASSESSMENT_HEADER"."MONTH" IS '評価月';
COMMENT ON COLUMN "ASSESSMENT_HEADER"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "ASSESSMENT_HEADER"."UPDATED_AT" IS '更新日時';

CREATE TABLE "ASSESSMENT_DETAIL" (
  "ASSESSMENT_ID" NUMBER(9) NOT NULL,
  "SEQ" NUMBER(9) NOT NULL,
  "ASSESSMENT_ITEM_ID" NUMBER(9) NOT NULL,
  "VALUE" NUMBER(9) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_ASSESSMENT_DETAIL PRIMARY KEY ("ASSESSMENT_ID", "SEQ", "ASSESSMENT_ITEM_ID"),
  CONSTRAINT FK_ASSESSMENT_ASSESSMENT_DETAIL FOREIGN KEY ("ASSESSMENT_ID") REFERENCES "ASSESSMENT_HEADER" ("ASSESSMENT_ID"),
  CONSTRAINT FK_ASSESSMENT_ASSESSMENT_ITEM FOREIGN KEY ("ASSESSMENT_ITEM_ID") REFERENCES "ASSESSMENT_ITEM" ("ASSESSMENT_ITEM_ID")
);

COMMENT ON TABLE "ASSESSMENT_DETAIL" IS '評価詳細';
COMMENT ON COLUMN "ASSESSMENT_DETAIL"."ASSESSMENT_ID" IS '評価ID';
COMMENT ON COLUMN "ASSESSMENT_DETAIL"."SEQ" IS 'シーケンス';
COMMENT ON COLUMN "ASSESSMENT_DETAIL"."VALUE" IS '評価値';
COMMENT ON COLUMN "ASSESSMENT_DETAIL"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "ASSESSMENT_DETAIL"."UPDATED_AT" IS '更新日時';
