CREATE SEQUENCE "USER_SEQ" START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "USER" (
  "USER_ID" NUMBER(9) DEFAULT NOT NULL,
  "GROUP_ID" NUMBER(9) NOT NULL,
  "FULL_NAME" VARCHAR2(50 CHAR) NOT NULL,
  "EMAIL" VARCHAR2(50 CHAR) NOT NULL,
  "PASSWORD" CHAR(64) NOT NULL,
  "BIRTHDAY" DATE NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  "UPDATED_AT" TIMESTAMP DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY ("USER_ID"),
  CONSTRAINT FK_USER_GROUP FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("GROUP_ID")
);

COMMENT ON TABLE "USER" IS 'ユーザー';
COMMENT ON COLUMN "USER"."USER_ID" IS 'ユーザID';
COMMENT ON COLUMN "USER"."GROUP_ID" IS 'グループID';
COMMENT ON COLUMN "USER"."FULL_NAME" IS '氏名';
COMMENT ON COLUMN "USER"."EMAIL" IS 'メールアドレス';
COMMENT ON COLUMN "USER"."PASSWORD" IS 'パスワード（SHA-256でハッシュ化した値を保存）';
COMMENT ON COLUMN "USER"."BIRTHDAY" IS '誕生日';
COMMENT ON COLUMN "USER"."CREATED_AT" IS '登録日時';
COMMENT ON COLUMN "USER"."UPDATED_AT" IS '更新日時';
