ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLESPACE APP_TS
    DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/app_ts.dbf'
    SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 2G;

CREATE USER APP IDENTIFIED BY oracle
    DEFAULT TABLESPACE APP_TS;
GRANT CREATE SESSION TO APP;
GRANT RESOURCE TO APP;
GRANT CREATE VIEW TO APP;
ALTER USER APP QUOTA UNLIMITED ON APP_TS;

CREATE USER WEB IDENTIFIED BY oracle;
GRANT CREATE SESSION TO WEB;
